### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [jonianven/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jonianven** [comment]
Hi Billy, 

Using the Bootstrap documentation [here](http://getbootstrap.com/css/#overview-mobile), added 

`<metaname="viewport" content="width=device-width, initial-scale=1">`

to `<head>` in application.html.erb. Changes are live and appear to have fixed the problem for mobile devices. Is this what you were looking for? 

Thanks for the feedback!

**Comment by BillyMassey** [comment]
That's it! Good Job 👍
